/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "brick_game/tetris/checkmk.basic_complete.ts" instead.
 */

#include <check.h>

#line 1 "brick_game/tetris/checkmk.basic_complete.ts"
// https://libcheck.github.io/check/doc/doxygen/html/check_8h.html
// https://www.mankier.com/1/checkmk
#include <stdio.h>
#include "brick_game/brickgame.h"
#include "brick_game/tetris/tetris.h"




START_TEST(NULL_ADD)
{
#line 13
updateCurrentState();
userInput(Start, false);
userInput(Down, true);
userInput(Down, true);
userInput(Down, true);
userInput(Down, true);
userInput(Right, false);

struct timespec req = {18, 500000000};  // 1.5 секунды
nanosleep(&req, NULL);  // Задержка на 1.5 секунды

userInput(Action, false);
userInput(Pause, false);
userInput(Pause, false);
userInput(Pause, false);

char exp[] =
    "\n..........\n"
    "..........\n"
    "..........\n"
    ".....#....\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........\n"
    ".....#....\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........\n"
    "..........";

char res[] =
    "\n          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          \n"
    "          ";

GameInfo_t info = updateCurrentState();

size_t i2 = 0;
for (size_t i = 0; i < NELEMS(exp) - 1; ++i) {
  if (exp[i] != '\n') {
    res[i] = (info.field[i2 / FIELD_COLS][i2 % FIELD_COLS]) ? '#' : '.';
    ++i2;
  }
}
ck_assert_msg(1, "Failed123445");

}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("NULL_TEST");
    TCase *tc1_1 = tcase_create("NULL_TEST");
    SRunner *sr = srunner_create(s1);
    int nf;

    /* User-specified pre-run code */
#line 85
  tcase_set_timeout(tc1_1, 30);
  printf("\033[0;36m");  // бирюзовый (Passed Failed)
    

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, NULL_ADD);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    /* User-specified post-run code */
#line 89
  printf("\033[0;31m"); // красный (CHECK.H Failures: N)
  if (nf != 0) {
    printf("CHECK.H Failures: %d\n", nf);
  }
  printf("\033[0;35m");  // розовый (VALGRIND)
  return 0;
}
